#!/bin/bash
count=0

for i in *;do 
  count=$((count+1))
  if [ $count -gt 6 ] 
    then count=1 
     fi
       if [ -d "$i/.svn" ]; then
         cd "$i" || exit ;tput setaf $count && \
         echo "$i": && echo -n ".......................:.s.v.n. " ;svn up;cd ..
         elif [ -d "$i/.git" ]; then
         cd "$i" || exit ;tput setaf $count && \
         echo "$i:" && echo -n ".......................:.g.i.t. " ;git pull;cd .. 
         elif [ -d "$i/CVS" ]; then
         cd "i" || exit ;tput setaf $count && \
         echo "$i:"  && echo -n ".......................:.c.v.s. " ;cvs up;cd ..
         tput sgr0
  fi
done 
